server:
  port: 9500
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: SELECT 1
      max-lifetime: 30000
      maximum-pool-size: 10
      minimum-idle: 3
    url: jdbc:mysql://192.168.99.230:3306/taotao-cloud-uc-center?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.taotao.cloud.code.model
