# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

# 配置：https://dependabot-gitlab.gitlab.io/dependabot/config/configuration.html

version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    auto-merge: true
    # 默认：5
    open-pull-requests-limit: 5
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      time: "05:00"
      timezone: "Asia/Shanghai"

  - package-ecosystem: "npm"
    directory: "/passport-ui"
    auto-merge: true
    # 默认：5
    # 设置为 1，防止 @typescript-eslint/parser、@typescript-eslint/parser 更新时出现冲突
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
      time: "05:00"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "npm"
    directory: "/ui"
    auto-merge: true
    # 默认：5
    # 设置为 1，防止 @typescript-eslint/parser、@typescript-eslint/parser 更新时出现冲突
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
      time: "05:00"
      timezone: "Asia/Shanghai"

  - package-ecosystem: "docker"
    directory: "/admin-server"
    auto-merge: true
    schedule:
      interval: "weekly"
      time: "05:00"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "docker"
    directory: "/gateway"
    auto-merge: true
    schedule:
      interval: "weekly"
      time: "05:00"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "docker"
    directory: "/passport"
    auto-merge: true
    schedule:
      interval: "weekly"
      time: "05:00"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "docker"
    directory: "/resource-services-parent/canal"
    auto-merge: true
    schedule:
      interval: "weekly"
      time: "05:00"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "docker"
    directory: "/resource-services-parent/file"
    auto-merge: true
    schedule:
      interval: "weekly"
      time: "05:00"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "docker"
    directory: "/resource-services-parent/master-data"
    auto-merge: true
    schedule:
      interval: "weekly"
      time: "05:00"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "docker"
    directory: "/resource-services-parent/user"
    auto-merge: true
    schedule:
      interval: "weekly"
      time: "05:00"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "docker"
    directory: "/resource-services-parent/webservice"
    auto-merge: true
    schedule:
      interval: "weekly"
      time: "05:00"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "docker"
    directory: "/resource-services-parent/websocket"
    auto-merge: true
    schedule:
      interval: "weekly"
      time: "05:00"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "docker"
    directory: "/resource-services-parent/wechat-miniprogram"
    auto-merge: true
    schedule:
      interval: "weekly"
      time: "05:00"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "docker"
    directory: "/resource-services-parent/wechat-offiaccount"
    auto-merge: true
    schedule:
      interval: "weekly"
      time: "05:00"
      timezone: "Asia/Shanghai"
  - package-ecosystem: "docker"
    directory: "/xxl-job-admin"
    auto-merge: true
    schedule:
      interval: "weekly"
      time: "05:00"
      timezone: "Asia/Shanghai"

  - package-ecosystem: "docker"
    directory: "/ui"
    auto-merge: true
    schedule:
      interval: "weekly"
      time: "05:00"
      timezone: "Asia/Shanghai"
