name: assemble open

on:
  push:
    paths:
      - 'taotao-cloud-ui/taotao-cloud-vue3-open/**'
    branches: [ open ]
    #branches: [ master ]
  pull_request:
    branches: [ open ]
    #branches: [ master ]

defaults:
  run:
    working-directory: ./taotao-cloud-ui/taotao-cloud-vue3-open

env:
  TAOTAO_CLOUD_VERSION: 2022.12

jobs:
  assemble:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'taotao-cloud-open') }}
    steps:
      - name: checkout project
        uses: actions/checkout@v3

      - name: use node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: cache node_modules folder
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-node_modules
          restore-keys: ${{ runner.os }}-node_modules

      - name: get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: cache yarn
        uses: actions/cache@v3
        env:
          cache-name: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: yarn install and build
        run: |
          yarn
          yarn build

      - name: deploy to server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "taotao-cloud-ui/taotao-cloud-vue3-open/dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_OPEN_TARGET }}

      - name: pulish docker image taotao-cloud-open
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: registry.cn-hangzhou.aliyuncs.com/taotao-cloud-project/taotao-cloud-open
          username: ${{ secrets.TAOTAO_CLOUD_REGISTRY_USERNAME }}
          password: ${{ secrets.TAOTAO_CLOUD_REGISTRY_PASSWORD }}
          registry: registry.cn-hangzhou.aliyuncs.com
          buildoptions: "--compress --force-rm"
          tags: "${{env.TAOTAO_CLOUD_VERSION}}"
          workdir: ${{ github.workspace }}/taotao-cloud-ui/taotao-cloud-vue3-open

      - name: send failure dingding notify
        if: failure()
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DING_TOKEN }}
          secret: ${{ secrets.DING_SECRET  }}
          body: |
            {
              "msgtype": "link",
              "link": {
                  "text": "taotao-cloud-open 开放平台构建失败",
                  "title": "github action",
                  "picUrl": "",
                  "messageUrl": "https://github.com/shuigedeng/taotao-cloud-project/actions/runs/${{github.action_id}}"
              }
            }

      - name: send success dingding notify
        if: success()
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DING_TOKEN }}
          secret: ${{ secrets.DING_SECRET  }}
          body: |
            {
              "msgtype": "link",
              "link": {
                  "text": "taotao-cloud-open 开放平台构建成功",
                  "title": "github action",
                  "picUrl": "",
                  "messageUrl": "https://github.com/shuigedeng/taotao-cloud-project/actions/runs/${{github.run_id}}"
              }
            }

#      - name: show runner
#        run: echo "$RUNNER_CONTEXT"
#        env:
#          RUNNER_CONTEXT: ${{ toJSON(runner) }}
#
#      - name: show github
#        run: echo "$GITHUB_CONTEXT"
#        env:
#          GITHUB_CONTEXT: ${{ toJSON(github) }}

#      - name: login to registry
#        uses: docker/login-action@v1
#        with:
#          registry: registry.cn-hangzhou.aliyuncs.com
#          username: ${{ secrets.TAOTAO_CLOUD_REGISTRY_USERNAME }}
#          password: ${{ secrets.TAOTAO_CLOUD_REGISTRY_PASSWORD }}

#      - name: build docker image taotao-cloud-open
#        run: |
#          docker build --tag registry.cn-hangzhou.aliyuncs.com/taotao-cloud-project/taotao-cloud-open:${{env.TAOTAO_CLOUD_VERSION}} .
#          docker push registry.cn-hangzhou.aliyuncs.com/taotao-cloud-project/taotao-cloud-open:${{env.TAOTAO_CLOUD_VERSION}}
